name: Daily Weather Prediction

on:
  schedule:
    - cron: '0 7 * * *'  # tous les jours à 7h UTC = 8h heure suisse
  workflow_dispatch:     # permet aussi de le lancer manuellement

jobs:
  run-prediction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily update
        run: python app/daily_update.py

      - name: Commit predictions
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add predictions/*.json
          git commit -m " Daily predictions: $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push
